commands/env.go
commands/version.go
common/hugo/semver-version.go
common/hugo/version-gotham.go
common/hugo/version.go
common/hugo/version_current.go
go.mod
go.sum
modules/config_test.go

Setup Gotham with its own versioning, separate from Hugos.
Here's thoughts for the future of `gotham version`: https://github.com/gothamhq/gotham/issues/17

Setup Gotham versioning.

---

common/hugo/version-gotham.go

This is the very first release of Gotham, a static site generator built
on the great Hugo project.
The first release of Gotham is mainly a cosmetic change of Hugo. Sites,
themes, and modules should be 100% compatible between Gotham and Hugo.
No unique features were added in this release.
Gotham v0.1.0 (compatible with Hugo v0.72.0/extended)

Release: Gotham v0.1.0

---

commands/env.go
commands/genautocomplete.go
commands/gendoc.go
commands/genman.go
commands/import_jekyll.go
commands/limit_darwin.go
commands/mod.go
commands/server.go
hugolib/config.go
hugolib/site_render.go

Swap Hugo for Gotham in command help text.

---

common/hugo/version-gotham.go

This is the second release of Gotham, including unique features which are described below.
In this release we added:
- Sitemap Page Exclusion
- The ability to add a flag to remove a page from the sitemap
- Support for Menue Items to Open Link in New Tabs
- Open Development Site in Browser
- Support for Snap and Homebrew
For more information on the above please visit gotham-features.md
Gotham v0.2.0 (compatible with Hugo v0.72.0/extended)

Release: Gotham v0.2.0

---

common/hugo/hugo.go
common/hugo/hugo_test.go
hugolib/template_test.go

Changing Hugo to Gotham 

---

snap/snapcraft.yaml

Snap: Fix --open flag for browser opening.

---

releaser/git_test.go

Update tests to use Gotham tags.

---

gotham-features.md
hugolib/embedded_shortcodes_test.go
tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/shortcodes/youtube.html

shortcode: Allow custom title for YouTube.

---

gotham-development.md

docs: Add dev note about RAM usage.

---

.circleci/config.yml
magefile-gotham.go

Add a Gotham specific Magefile.

---

.circleci/config.yml

Produces and stores a JUNIT file for both Linux and macOS with Linux uploading to the CircleCI Test Summary --- which currently does **nothing** :cry:

Produce and store JUNIT test output.

---

.circleci/config.yml

Update to the latest GoReleaser and Mage.

Bump versions of build tools.

---

.circleci/config.yml
.gitignore
src/magefile-gotham.go

Add Codecov for test coverage.

---

.gitignore

Now that the codebase was moved, where the binary will be created was also moved.

Correct where the gotham binary will be generated.

---

.github/CODEOWNERS

This will automatically add @chayev or myself as the reviewer.

Add a codeowners file.

---

scripts/fork-tests.sh

Adding a test to make sure we don't accidently import packages from the upstream project.

Test for upstream package usage.

---

maintainer.md

Adds a maintainer note related to the new test added.

Add maintainer note.

---

gotham-features.md
src/go.mod
src/go.sum
src/hugolib/embedded_shortcodes_test.go
src/tpl/gotham/gotham.go
src/tpl/gotham/gotham_test.go
src/tpl/gotham/init.go
src/tpl/gotham/init_test.go
src/tpl/tplimpl/embedded/templates.autogen.go
src/tpl/tplimpl/embedded/templates/shortcodes/qrcode.html
src/tpl/tplimpl/template_funcs.go

Add a template function to generate QR codes in Gotham.

Add QR code gen support to Gotham.

---

src/common/hugo/semver-version.go
src/common/hugo/semver-version_test.go

adding in logic to only add hash in dev

---

gotham-features.md
src/config/services/servicesConfig.go
src/hugolib/asset_links_test.go
src/hugolib/page__new.go
src/hugolib/page_kinds.go
src/hugolib/site.go
src/hugolib/site_output.go
src/hugolib/site_render.go
src/tpl/tplimpl/embedded/templates.autogen.go
src/tpl/tplimpl/embedded/templates/_default/assetlinks.json

Closes #204. 
Add support for Google Digital Asset Links to connect an Android app to your website.

Tpl: add support for Digital Asset Links.

---

src/hugolib/testhelpers_test.go

Adds a function that I'm sure we'll need at some point. This basically completes a testing function duo that already exists for SiteBuilder.

Add a testHelper function for files.

---

src/commands/commands.go
src/commands/commands_test.go
src/commands/hugo_test.go
src/commands/new_site.go

Default site new and config to YAML.
