gothamhq/gotham

.circleci/config.yml
.travis.yml
goreleaser.yml
hugolib/hugo_modules_test.go
hugolib/hugo_sites_build_errors_test.go
magefile.go
releaser/releaser.go

From Hugo, CircleCI was exclusively used for releases only. This PR enables CircleCI to do complete testing on Gotham.
It also has a few tweaks to the existing Travis CI build to work with Gotham.
Closes #3.

Setup initial CircleCI config and fix Travis CI.

---

CONTRIBUTING.md

This is a first pass of replacing details on how to contribute to the Hugo project.
We will need to update references to our Docs and Forum once those are up. As of now all users are pointed to open Issues.

meta: Updated instructions to contribute to Gotham.

---

.circleci/config.yml
common/para/para_test.go

We had to fix an extremely flaky test in this PR in order to get macOS tests to pass reliably. This likely wasn't even tested in Hugo because the test is activated with four or more CPU cores. Travis and Linux on CircleCI has 2 cores. macOS CircleCI however has 4 cores.
We have a follow up Issue in order to improve this test in the near future: https://github.com/gothamhq/gotham/issues/8

Add macOS CircleCI job.

---

.circleci/config.yml
.goreleaser.linux.yml
.goreleaser.macos.yml
.goreleaser.windows.yml
common/hugo/version.go
common/hugo/version_current.go
modules/config_test.go

GoReleaser is setup to support releasing from Linux and macOS. For now, changelogs are off since we don't have any releases yet.

Setup GoReleaser for Linux & macOS.

---

.goreleaser.linux.yml
.goreleaser.macos.yml

Make the checksum files between Linux and macOS have unique names. This
will prevent a failed CI build during releases going forward.
Aside from the main change, there's spaces added to some template tags to make them more consistent. I also add a newline before every top level key, again for legibility.
Fixes #21.

Correct checksum file naming.

---

commands/version.go
common/hugo/semver-version.go

Added the flag support for short and detailed.
Here's an example of output for the dev version:
```bash
Gotham v0.2.0-dev (compatible with Hugo v0.72.0/extended)
BuildDate: unknown
Platform: linux/amd64
```
Closes #17.

Enhance the version command.

---

config/commonConfig.go
hugolib/sitemap_test.go
tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/_default/sitemap.xml

This PR adds a new key to .Sitemap called `Exclude`. `Exclude` is a
boolean that is set to false by default meaning all available pages are
included. This is the behavior currently. When `Exclude` is set to true,
it will not appear in any `sitemap.xml` files that Hugo may generate.
`Exclude` can be set to true in the Hugo config turning `sitemap.xml`
into an opt-in rather than an opt-out.
fixes: #28

Enable page exclusion from sitemap.xml

---

gotham-features.md
hugolib/menu_test.go
navigation/menu.go

Adds the ability for a Gotham menu item to say its URL should be opened in a new tab.
Closes: #29

Add NewTab property to Gotham menus

---

.circleci/config.yml
.goreleaser.linux.yml

This PR contains two related changes.
1. It enables static binaries for the Linux release. Right now, this helps us in the work for #25. Now the Linux binary will run on Ubuntu 19.10 and within the snap (currently Ubuntu 18.04) without an issue. In the future, this will let us run on my Linux distros (amd64) without a problem.
2. This re-arranches the CircleCI jobs into 2 workflows. For everyday commits, the "main" workflow runs, running the two test jobs and two GoReleaser jobs all in parallel. GoReleaser will just build snapshots and not publish to GitHub. The "release" workflow only runs on releases (when we tag with a SemVer version) and runs both test jobs BEFORE the release jobs.

Goreleaser static snapshots

---

hugolib/gotham-genertor_test.go
hugolib/testhelpers_test.go
transform/metainject/hugogenerator.go

Generates the HTML meta data with Gotham rather than Hugo.
Before change:
```
<meta name="generator" content="Hugo 0.72.0" />
```
After change:
```
<meta name="generator" content="Gotham 0.1.0" />
```
Closes: #32

Use Gotham rather than Hugo in HTML meta generator tag.

---

.goreleaser.macos.yml

Adds support for GoReleaser to update our Homebrew Tap upon release. (https://github.com/gothamhq/homebrew-tap).
Closes #26.

Brew tap support

---

.circleci/config.yml

The CircleCI Go orb has been updated. The new release (v1.3.0) includes:
- binary caching
- macOS support
Both we can use. This PR implements it.

Use Go orb install on macOS.

---

resources/page/page_marshaljson.autogen.go
tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/_default/rss.xml

Updated rss generator tag to reference Gotham in tpl/tplimpl/embedded/templates/_default/rss.xml
I also ran `mage generate` after the change and it updated two files.
closes: #60

Update generator tag in RSS templates

---

commands/commandeer.go
common/hugo/version.go

Changed the function that is called when an error is caught in browser.
Reset BuildVersionString() to reference Hugo.
Closes: #61

Error message update

---

common/hugo/version-gotham.go

v0.3.0 of Gotham includes additional minor cosmetic changes. The only
significant change in this release is the inclusion of Hugo v0.73.0.
Gotham v0.3.0 (compatible with Hugo v0.73.0/extended)

Release: Gotham v0.3.0

---

.circleci/config.yml
scripts/timestamp-generator.sh

Resets the Go build/test cache every 4 days.

CI: Implement a go test cache interval.

---

maintainer.md

Creating a place for us to document maintainer procedures.
Closes #19.

Docs: Add maintainer notes. [skip ci]

---

common/hugo/version-gotham.go

This release of Gotham includes updates from Hugo v0.74.1.
There were no other significant changes to the code base.
Gotham v0.4.0 (compatible with Hugo v0.74.1/extended)

Release: Gotham v0.4.0

---

.circleci/config.yml
scripts/fork-tests.sh

A small collection of tests to help make sure the repo remains the way we expect it to. This should help capture issues with pulling upstream.

Add fork tests.

---

common/hugo/version-gotham.go

This release of Gotham includes changes from Hugo v0.74.2.
Gotham v0.5.0 (compatible with Hugo v0.74.2/extended)
---
Went with a minor release because there's a lot of work to cherry pick the upstream changes. Especially since, with the double merge commits, not all pieces show a commit hash.

Release: Gotham v0.5.0

---

gotham-features.md
hugolib/embedded_shortcodes_test.go
tpl/tplimpl/embedded/templates.autogen.go
tpl/tplimpl/embedded/templates/shortcodes/youtube.html

Closes #83.
Also tested on my personal website to make sure the start/stop parameters actually work with a real video.

shortcode: Allow start/stop params for YouTube.

---

common/hugo/version-gotham.go

This release of Gotham includes an update to Youtube Shortcode and changes from Hugo v0.74.3.
YouTube Shortcode updates include:
- The shortcode has a title parameter.
- The shortcode has start and stop parameters, measured in seconds.
The above is also included in gotham-features.md for reference.
Gotham v0.6.0 (compatible with Hugo v0.74.3/extended)

Release: Gotham v0.6.0

---

.circleci/config.yml
magefile.go

Moving forward, the majority of the changes that we make for Mage to
Gotham can be done in its own file. This allows us to touch Hugo's as
little as possible, making handling conflicts easier in the future.
The parts of the Magefile that continue to be different after this PR
need to be different in order for the Magefile to work for our project.
An additional, Gotham-specific Magefile will come in a separate PR.

Mostly restore original Hugo Magefile

---

.goreleaser.linux.yml
.goreleaser.macos.yml

We were missing the commit hash for both macOS and Linux. This adds that back.
Also, replaced [a deprecated term](https://goreleaser.com/deprecations/) for Brew in GoReleaser.

Fix GoReleaser files.

---

src/hugolib/page_test.go

This fixes an error with a test that was caused when the Go code was moved to the src folder. The test is looking at the last modified date of test files, which changed due to the code move.

Update lastMod date in page_test.go to current date

---

src/markup/goldmark/goldmark_config/config.go

The Goldmark.Renderer.Unsafe was updated to be true by default. This allows for the use of HTML in the markdown files.
This value could be disabled by passing the below:
```
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
```
closes: #39

Change Goldmark Renderer Unsafe to true by default

---

src/commands/new_theme.go
src/hugolib/config_test.go

When creating a new theme, the files created reference a URL that does not exist. Corrected the reference in this PR.

theme: undo URL change.

---

maintainer.md

Minor updates to maintainer files:
- Updated path to [version-gotham.go](https://github.com/gothamhq/gotham/blob/master/src/common/hugo/version-gotham.go)
- Corrected reference of [version_current.go](https://github.com/gothamhq/gotham/blob/master/src/common/hugo/version_current.go#L7)
- Updated test command to `mage -v testGotham`

Update maintainer guide with new src directory and GoTestSum.

---

src/common/hugo/version-gotham.go

This release of Gotham includes a Windows binary and also enables you to use HTML in your markdown files by default.
This release also includes updates from Hugo v0.75.1.
Gotham v0.7.0 (compatible with Hugo v0.75.1/extended)

Release: Gotham v0.7.0

---

src/common/hugo/version-gotham.go

This release is just to include Hugo v0.77 and the three point releases
that came after it.
Gotham v0.8.0 (compatible with Hugo v0.77.0/extended)

Release: Gotham v0.8.0

---

src/common/hugo/version-gotham.go

Updating the internal Hugo code to Hugo v0.79.0.
Gotham v0.8.0 (compatible with Hugo v0.79.0/extended)

Release: Gotham v0.9.0

---

gotham-features.md
src/hugolib/embedded_shortcodes_test.go
src/tpl/tplimpl/embedded/templates.autogen.go
src/tpl/tplimpl/embedded/templates/shortcodes/mastodon.html

Closes #197. 
Adds a shortcode to embed toots from [Mastodon](https://joinmastodon.org/).

Tpl: add support for Mastodon shortcode.

---

src/common/hugo/version-gotham.go

This is a decent size release for Gotham. It includes new shortcodes and
templates as well as a small bug fix. Enjoy!
New features:
- a shortcode for QR code generation
- support for Google's Digital Asset Links
- a shortcode for Mastodon
Fixes:
- Gotham no longer shows the commit hash via the version command for
official releases
Gotham v0.10.0 (compatible with Hugo v0.79.0/extended)

Release: Gotham v0.10.0

---

gotham-features.md
src/config/services/servicesConfig.go
src/hugolib/aasa_test.go
src/hugolib/page_kinds.go
src/hugolib/site.go
src/hugolib/site_output.go
src/hugolib/site_render.go
src/tpl/tplimpl/embedded/templates.autogen.go
src/tpl/tplimpl/embedded/templates/_default/apple_app_site_association.json

Closes #203 
Add support for the Apple App Site Association file to connect an iOS app to your website.

Tpl: add support for Apple App Site Association.

---

src/common/hugo/version-gotham.go

This Gotham release includes a few exciting updates.
It includes support for Apple's App Site Association and JSON Feed.
New features:
- support for Apple's App Site Association
- support for JSON Feed
Gotham v0.11.0 (compatible with Hugo v0.79.1/extended)

Release: Gotham v0.11.0

---

src/common/hugo/version-gotham.go

Includes changes from the Hugo v0.80.0 release.
One notable piece is the switch from LibSass to Dart Sass for SCSS/SASS
processing.
Gotham v0.12.0 (compatible with Hugo v0.80.0/extended)

Release: Gotham v0.12.0

---

src/common/hugo/version-gotham.go

This release adds v1 support for AASA links. Gotham now supports both v1
(pre-2019) and v2 (2019 and on) AASA schemas thanks to @chayev.
This release is also the last one to be called Gotham. Starting with the
v0.14.0 release Gotham will now be called Strawberry. To continue to
receive updates to Strawberry/Gotham you'll need to reinstall it. This
can be done by following the migration guide:
https://docs.strawberryssg.com/migration
Gotham v0.13.0 (compatible with Hugo v0.80.0/extended)

Release: Gotham v0.13.0
